# Generated by Django 3.1.2 on 2021-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_auto_20210512_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='Rate',
            new_name='rate',
        ),
        migrations.AlterField(
            model_name='artist',
            name='hometown',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=99, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
