# Generated by Django 3.1.2 on 2021-05-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0004_note_photo'),
        ('lmn', '0005_auto_20210502_2351'),
    ]

    operations = [
    ]
