# Generated by Django 3.1.2 on 2021-05-12 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0005_auto_20210511_2327'),
        ('lmn', '0007_auto_20210509_1955'),
    ]

    operations = [
    ]
